# Generated by Django 4.2.7 on 2023-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=200),
        ),
    ]
