# Generated by Django 4.2.7 on 2023-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
