# Generated by Django 4.2.7 on 2023-12-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payment_level_payment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
    ]
