# Generated by Django 4.2.7 on 2023-12-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_payment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='level',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='level',
            new_name='student_class',
        ),
    ]
