# Generated by Django 4.2.7 on 2023-12-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('Basic 1', 'Basic 1'), ('Basic 2', 'Basic 2'), ('Basic 3', 'Basic 3'), ('Basic 4', 'Basic 4'), ('Basic 5', 'Basic 5'), ('Basic 6', 'Basic 6')], default='Basic 1', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
